const APP = {
	CONNECT_REQUEST: 'CONNECT_REQUEST',
	CONNECT_SUCCESS: 'CONNECT_SUCCESS',
	CONNECT_FAILURE: 'CONNECT_FAILURE',
	DISCONNECT: 'DISCONNECT',
};

const MAPPINGS = {
	MAPPINGS_FETCH_REQUEST: 'MAPPINGS_FETCH_REQUEST',
	MAPPINGS_FETCH_SUCCESS: 'MAPPINGS_FETCH_SUCCESS',
	MAPPINGS_FETCH_FAILURE: 'MAPPINGS_FETCH_FAILURE',
};

export { APP, MAPPINGS };
