const APP = {
	CONNECT_REQUEST: 'CONNECT_REQUEST',
	CONNECT_SUCCESS: 'CONNECT_SUCCESS',
	CONNECT_FAILURE: 'CONNECT_FAILURE',
	DISCONNECT: 'DISCONNECT',
	DISMISS_APP_CONNECT_ERROR: 'DISMISS_APP_CONNECT_ERROR',
};

const MAPPINGS = {
	MAPPINGS_FETCH_REQUEST: 'MAPPINGS_FETCH_REQUEST',
	MAPPINGS_FETCH_SUCCESS: 'MAPPINGS_FETCH_SUCCESS',
	MAPPINGS_FETCH_FAILURE: 'MAPPINGS_FETCH_FAILURE',
	ADD_MAPPING_REQUEST: 'ADD_MAPPING_REQUEST',
	ADD_MAPPING_SUCCESS: 'ADD_MAPPING_SUCCESS',
	ADD_MAPPING_FAILURE: 'ADD_MAPPING_FAILURE',
	SET_VISIBLE_COLUMNS: 'SET_VISIBLE_COLUMNS',
};

const CELL = {
	CELL_ACTIVE: 'CELL_ACTIVE',
	CELL_HIGHLIGHT: 'CELL_HIGHLIGHT',
	CELL_SETVALUE_REQUEST: 'CELL_SETVALUE_REQUEST',
	CELL_SETVALUE_SUCCESS: 'CELL_SETVALUE_SUCCESS',
	CELL_SETVALUE_FAILURE: 'CELL_SETVALUE_FAILURE',
};

const DATA = {
	ADD_DATA_REQUEST: 'ADD_DATA_REQUEST',
	ADD_DATA_SUCCESS: 'ADD_DATA_SUCCESS',
	ADD_DATA_FAILURE: 'ADD_DATA_FAILURE',
};

export { APP, CELL, DATA, MAPPINGS };
