import appbase from 'appbase-js';
import { parseUrl } from '../utils';

const addData = async (app, rawUrl, data) => {
	try {
		const { url, credentials } = parseUrl(rawUrl);
		const api = appbase({
			app,
			url,
			credentials,
		});
		const res = await api.index({
			type: app, // currently only supports single type and autogenerated id
			body: data,
		});
		return res;
	} catch (error) {
		const errorMessage = error.statusText || 'Unable to index data'; // broken in appbase-js, need to fix it later
		throw new Error(errorMessage);
	}
};

export default addData;
